# deprecations after 0.6
@deprecate freqz(filter::FilterCoefficients{:z}) freqresp(filter, range(0, stop=π, length=250))
@deprecate freqz(filter::FilterCoefficients{:z}, w) freqresp(filter, w)
@deprecate freqs(filter::FilterCoefficients{:s}, w) freqresp(filter, w)
@deprecate freqz(filter::FilterCoefficients{:z}, hz, fs) freqresp(filter, hz, fs)
@deprecate freqs(filter::FilterCoefficients{:s}, hz, fs) freqresp(filter, hz, fs)
@deprecate phasez(filter::FilterCoefficients{:z}) phaseresp(filter, range(0, stop=π, length=250))
@deprecate phasez(filter::FilterCoefficients{:z}, w) phaseresp(filter, w)
@deprecate grpdelayz(filter::FilterCoefficients{:z}) grpdelay(filter, range(0, stop=π, length=250))
@deprecate grpdelayz(filter::FilterCoefficients{:z}, w) grpdelay(filter, w)
@deprecate impz(filter::FilterCoefficients{:z}) impresp(filter)
@deprecate impz(filter::FilterCoefficients{:z}, n) impresp(filter, n)
@deprecate stepz(filter::FilterCoefficients{:z}) stepresp(filter)
@deprecate stepz(filter::FilterCoefficients{:z}, n) stepresp(filter, n)
